[project]
name = "HiThere"
version = "0.1.0"
description = ""
authors = ["Virat Kaushal viratkaushal1212@gmail.com"]
requires-python = ">=3.11"
dependencies = [
    "flask-socketio==5.3.6",
    "flask>=3.1.1",
    "python-socketio==5.10.0",
]
